fix NoSuchMethodError in JavaConverters in ScalaTestRunner for Scala 2.13.0-RC3 #SCL-15558 fixed
(cherry picked from commit 76e69f2601635ac0867f2970b942cc04255c4000)